# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c9E-lll5Cy8LR6XcQ6ZHa_Nio_OJmFGN
"""

import streamlit as st
from PIL import Image

# Configuración de la página
st.set_page_config(
    page_title="Visualización de Resultados | Grupo 6",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# Título principal
st.markdown("<h1 style='text-align: center; color: #4A90E2;'>📊 Dashboard de Resultados Finales</h1>", unsafe_allow_html=True)

# Subtítulo
st.markdown("<h4 style='text-align: center; color: gray;'>Proyecto: Análisis y Clasificación de Reseñas de Alimentos Finos de Amazon</h4>", unsafe_allow_html=True)

st.markdown("---")

# Lista de gráficos con descripciones enriquecidas
graficos = [
    {
        "archivo": "img/grafico_1.png",
        "descripcion": """
        ### 🥇 Gráfico 1: Distribución de Sentimientos por Categoría de Producto

        Este gráfico representa cómo se distribuyen los sentimientos de las reseñas (positivos, negativos y neutros) en cada una de las categorías de productos alimenticios.
        Es fundamental para detectar patrones emocionales de los clientes según el tipo de producto.
        Por ejemplo, si los productos “orgánicos” tienden a generar opiniones positivas y los “enlatados” negativas, la empresa puede tomar decisiones más estratégicas sobre inventario, marketing y atención al cliente.

        **Objetivo:** Identificar áreas problemáticas o destacables según la percepción emocional del consumidor.
        """
    },
    {
        "archivo": "img/grafico_2.png",
        "descripcion": """
        ### 📈 Gráfico 2: Frecuencias de Palabras en Reseñas Positivas

        Aquí observamos cuáles son las palabras más repetidas en reseñas altamente positivas (con calificación de 4 o 5 estrellas).
        Este análisis semántico permite identificar los elementos que generan mayor satisfacción, como “rápido”, “delicioso”, “natural”, “empaque”, entre otros.

        **Aplicación práctica:** Estos hallazgos pueden ser utilizados en campañas publicitarias, empaques o mejoras de producto, priorizando lo que realmente valoran los clientes.
        """
    },
    {
        "archivo": "img/grafico_3.png",
        "descripcion": """
        ### 🤖 Gráfico 3: Resultados del Modelo de Clasificación (Stacking)

        Se presenta la evaluación cuantitativa del modelo Stacking, un enfoque de ensamblaje que combina diferentes algoritmos para mejorar la precisión general.
        Las métricas mostradas incluyen **Accuracy**, **Precision**, **Recall** y **F1-score**, comparando el rendimiento con modelos individuales como Naive Bayes o SVM.

        **Conclusión clave:** El modelo de Stacking logra un balance óptimo entre sensibilidad y especificidad, siendo el más confiable para clasificar sentimientos en las reseñas.
        """
    },
    {
        "archivo": "img/grafico_4.png",
        "descripcion": """
        ### 🧠 Gráfico 4: Visualización de Embeddings de Reseñas (Reducción de Dimensiones)

        Esta visualización representa las reseñas en un espacio de baja dimensión (usando técnicas como t-SNE o PCA) para observar la cercanía semántica entre ellas.
        Reseñas similares aparecen agrupadas, lo que evidencia patrones ocultos en el lenguaje de los usuarios.

        **Utilidad:** Ayuda a validar que el modelo de procesamiento de texto capta relaciones contextuales entre palabras y frases, clave para tareas de clustering o análisis temático.
        """
    },
    {
        "archivo": "img/grafico_5.png",
        "descripcion": """
        ### ⚔️ Gráfico 5: Comparación Final de Modelos Clasificadores

        Este gráfico final realiza una comparación directa entre distintos modelos de aprendizaje supervisado: Naive Bayes, SVM, Random Forest y Stacking.
        Se muestran métricas como precisión y F1-score para validar cuál tiene mejor desempeño real.

        **Resultado destacado:** El modelo Stacking supera a los demás en la mayoría de métricas, demostrando que la combinación inteligente de clasificadores produce mejores resultados que usarlos por separado.

        **Reflexión final:** Esta evaluación permite tomar decisiones informadas sobre qué modelo implementar en producción o investigación futura.
        """
    }
]

# Selector
opciones = [f"Gráfico {i+1}" for i in range(len(graficos))]
seleccion = st.selectbox("📁 Selecciona un gráfico para visualizar:", opciones)
indice = opciones.index(seleccion)

# Mostrar imagen y descripción
img = Image.open(graficos[indice]["archivo"])
st.image(img, use_column_width=True)
st.markdown(graficos[indice]["descripcion"], unsafe_allow_html=True)

# Separador
st.markdown("---")

# Footer
st.markdown(
    "<p style='text-align: center; color: gray;'>Grupo 6 • Universidad César Vallejo • 2025</p>",
    unsafe_allow_html=True
)