[server]
maxUploadSize = 300  # Permite archivos de hasta 1000 MB (1 GB)
headless = true
port = 8501
enableXsrfProtection = true
# NOTA: No incluyas 'enableCORS = false' para evitar errores en plataformas como Render o Streamlit Cloud
